# Generated by Django 5.0.6 on 2024-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
